### ISSUE TITLE
[not an issue] Very simple request

### ISSUE THREAD

**Issue by EstherMoellman** [sagitta1618/tabContainer#1]
Hi @sagitta1618 ,

Firstly, thank you for your TabContainer.

Please, I have a very simple request: Can you change the label of your add-on? I mean the "priv9-". It'll be nicer if you change it, for example, to "TC" (temporary container). So, it'll appear as TC01, TC02, TC03... TC9999.

I believe "TC" + XXXX (number) is more than enough.
And it's more clean, minimalist, avoiding distractions and visual pollution.

If you're not going to change it, please, can you teach me how to change it with CSS?
I was able to eliminate the icon using "#userContext-indicator { display: none !important }". But I have no idea how to change the ugly "priv9-".

Thank you in advance!

**Comment by sagitta1618** [comment]
Hello @EstherMoellman 

Very good feature request! I updated the header to 'TC' instead of 'priv9-'. The 'priv9-' was a legacy from an older addon.

Thanks.

Please close the issue if that works for you.
