### ISSUE TITLE
Small issue: Some tabs are not opened in temporary containers

### ISSUE THREAD

**Issue by EstherMoellman** [sagitta1618/tabContainer#3]
Hi @sagitta1618 !

I found a small issue (while using [TabsToBoomakGroups - TTBG](https://addons.mozilla.org/en-US/firefox/addon/tabs-to-bookmark-groups/) add-on). As title says, sometimes in specific situations, some tabs are not opened in temporary containers (TC). Way to reproduce the issue:

1) Install TTBG => Go to about:add-ons + TTBG’ options check “Unload inactive tabs” => Restart.
2) Create a tab group (let's say Group01) with (let's say) 5 tabs.
3) Ensure these 5 tabs are fully loaded => Restart.
4) At Group01 and from the 5 tabs, randomly load 3 tabs. If the issue appears, then these 3 tabs are going to be opened without TC. But if the issue doesn't appear and these 3 tabs are opened in TC, then again ensure these 3 tabs are fully loaded => Restart => Open these (same) 3 tabs, and you will see the issue, these 3 tabs are going to be open without TC.

ADDITIONAL INFO:
- Even without TC, If you duplicate these 3 tabs, then they will open in TC.
- If you open the other 2 tabs, they always will open in TC (if these 2 tabs really were unloaded on previous browser session).
- If you create a Group02 and you go back to Group01, when you reopen these same 3 tabs (in Group01), now they will open in TC.

From my ignorance, apparently TC can't be opened on last loaded tabs, until these tabs are duplicated, or unloaded (discarded) and loaded (reopened) again. By "last loaded tabs" I mean "loaded tabs in previous browser session".

Thank you in advance and have a nice weekend! : )

**Comment by sagitta1618** [comment]
Hello @EstherMoellman,
I could reproduce the issue when I have the setting: 'Restore tabs from previous sessions' checked. Do you have this setting enable by any chance?

I think when this setting is enable, the browser remember the last opened tab and their given container but on next browser start, when it tries to load them, it finds that the container they were using got removed (because all TC are removed at browser start) and so they got loaded back into the default container.

Have a good weekend too!

**Comment by EstherMoellman** [comment]
Yeap @sagitta1618 , I do have "Restore tabs from previous sessions" checked. Sorry, I didn't mention it in my previous message because this setting is a must for all and every tab manager add-on. Most of these add-ons when you install them show an info page, requesting to check this setting. These add-ons don't work without this setting.

But I'm glad you reproduced the issue.
And I agree with you, the issue might be related to the "Restore tabs from previous sessions". However, the issue is not just with the "last" opened tab, it appears on all "last" opened tabs. For example, if you are in Group01 with 5 unloaded tabs, and you load 3 tabs with 3 different temporary containers, if you close the browser and restart it again, these 3 "last" opened tabs are going to open without containers. Using your logic, it seems that the "Restore tabs from previous sessions" tries to load **ALL** the "last" opened tabs, and it fails because TabContainer deletes everything on startup.

As usual, I hope you will find a solution. Count on me! : )

Zillions of thanks once again!

**Comment by sagitta1618** [comment]
@EstherMoellman can you give this a try?
[tempcontainer-1.1.4-fx.zip](https://github.com/sagitta1618/tabContainer/files/4808759/tempcontainer-1.1.4-fx.zip)

**Comment by EstherMoellman** [comment]
... first round of tests is a big **SUCCESS**! Congrats @sagitta1618 !
Tomorrow I'll do more nasty tests, but at first glance, your 1.1.4 passed the first round of tests, a preliminary signal that you fixed the issue (can be closed). At every normal scenario of opening and closing tabs, changing tab groups, closing and restarting the browser etc, everything seems to work fine, tabs are opened in temporary containers, and of course containers are remembered per session/cleaned on startup. PERFECT!
What a nice add-on you have! : )
Thank you!

**Comment by sagitta1618** [comment]
Great! I'll update this github and the official addon on AMO.
