### ISSUE TITLE
Pinned tabs with containers

### ISSUE THREAD

**Issue by EstherMoellman** [sagitta1618/tabContainer#4]
Hi @sagitta1618 !

I believe I found a new issue: Pinned tabs with temporary containers, when browser restarts, these pinned tabs become unpinned. Way to reproduce:
- FF' Nightly clean install latest version.
- Install TabContainer and restart browser.
- Open several tabs in temporary containers and pin them. Close browser.
- Restart browser: You will see pinned tabs jumping and becoming unpinned.

Big hug! : )

**Comment by sagitta1618** [comment]
Hello @EstherMoellman ,

Good debugging work. Can you try v1.1.5 and see if it fixes it? 
[tempcontainer-1.1.5-fx.zip](https://github.com/sagitta1618/tabContainer/files/4841408/tempcontainer-1.1.5-fx.zip)

**Comment by EstherMoellman** [comment]
... I only checked the pinned tabs issue, and your v.1.1.5 seems to solve it! Congrats and thanks! As usual, tomorrow I will do more tests, and I'll report you if I find something. But please, let me share with you two additional comments out of the topic:

1) Every time a temporary container is created, or an unloaded tab with temporary container is loaded again... there is a lot of movement in the tabbar. This is not happening only with your add-on, is happening with all temporary container add-ons. AFAIK this "tabbar movement" (is a kind of tab shacking before opening) partially is because the browser replaces the normal tab with a temporary container container tab, so the browser closes the normal tab and opens a new tab with temporary container, and this close/open appears as a shaking tabbar movement. But I wonder if you (please) can do something to minimize this (very) annoying tabbar movement. Just an idea: Instead of opening normal tabs as default, is not possible to open temporary container by default? If normal tabs (without containers) never are opened by default, and always by default temporary containers are opened, can this avoid the tabbar movement?

2) The name of your add-on is not good for the search function at AMO page. For example, if at search you write "tab", then your add-on never will appear. And if you write "container" also won't appear. Not to mention that the word "temporary" is really needed at the name of your add-on. So, just as a suggestion, what about: "Temporary Container Lite", or "Tab Temporary Container", or "Temporary Container Everywhere", or "Automatic Temporary Container" etc. This is just an irrelevant suggestion from my side, to incorporate the "temporary" word in the name, and to improve the AMO search results. You have the last word!

Big hug! : )

**Comment by sagitta1618** [comment]
Thanks for testing @EstherMoellman. I've update AMO with the fix and changed the name to 'Tab Temporary Container' (Thanks for the name :+1:). I acknowledge that unless you know what you exactly are searching for, it's hard to find "tabContainer" amongst the other extensions.
I'll keep issue 1) in mind. The moving around is because, to my knowledge, it's not possible to transfer a tab from one container to another, you always need to reopen the tab in a new container and close the old one. A way to fix that would be to catch "opening new tab" events but I am not sure those are emitted when tabs are 'restored' from previous session. I'll have to experiment with that a bit more :)
Thank you for you support!

**Comment by EstherMoellman** [comment]
... it's me who thank you for your add-on (very useful for my day-to-day browsing), and also thank you for your always fast modifications and solutions. You deserve all the merits here! : )

This "shaking tabbar movement" is horrible! Due to my studies/work, everyday I need to deal with tons of tabs, and every new tab is a kind of ugly earthquake in my tabbar, very distracting and annoying. Even a simple tab reload or tab duplication etc... always will shake the tabbar. Of course, 1 or 10 tabs are not the end of the world, but hundred of shaking tabs day after day for months... it is quiet irritating.

I blame Firefox in first place, because temporary container should be the built in default mode! (if users want normal tabs, they should change from TC default to no container or permanent container). In simple words, your add-on should be a FF' built in function + default mode. Sadly I can't convince FF, so if by chance you can fix (or at least you can reduce) this tabbar shacking... wowwwwwww, this will be something!... for your add-on it will be a new strong add-value, and personally for me will be F-A-N-T-A-S-T-I-C-! : )

Have a nice week!

PS: Feel free to close the issue.
