### ISSUE TITLE
tab bar shaking when reopening tab from previous session

### ISSUE THREAD

**Issue by sagitta1618** [sagitta1618/tabContainer#5]
when the session restore is checked, and the browser start, each time a tab will be loaded, that will shake the tab bar.
Possible fix:
- detect the create tab event and do the conversion to TC then (not sure it is fired on restored tab)
- detect the tab index and order the tab after loading them all (just for the start)

**Comment by sagitta1618** [comment]
solution now incorporates opening the new TC tab with the same index as the tab being closed.

**Comment by EstherMoellman** [comment]
Thank you @sagitta1618 ! Your fix indeed reduced the tab shacking. If you allow me a suggestion, this fix should be described in TabTemporaryContainer AMO' page. Your add-on is the only one reducing the tab shacking created by new tabs! I believe it's important to stress that at AMO' page.

PS1: If you allow me another suggestion, your GitHub and your AMO' page both show the old "Tab Container" name as part of the add-on name (when, of course, should be "Tab Temporary Container"). The old "Tab Container" name at AMO appears in the url address. And at GitHub appears as name and as url. I know you may lose links if you change the url, but IMO it's better to do that ASAP.

PS2: Something is wrong with number of users at AMO. Lot of people uses my Nightly' layout + my add-ons (including TabTemporaryContainer), and at AMO appears only 2 users.
